### ISSUE TITLE
Bug in EnsembleNormalizer 

### ISSUE THREAD

**Issue by jelarsso** [oslocyclotronlab/ompy#200]
There seems to be an issue related to the parallelization of EnsembleNormalizer. 

```
simnorm = om.NormalizerSimultan(normalizer_nld=nldnorm, normalizer_gsf=gsfnorm, regenerate=True)
# running faster than the default 400 given less precise answers
# For propper calc. you may rather increase this to > 400.
simnorm.multinest_kwargs["n_live_points"] = 300

simnorm.normalize(gsf=extractor.gsf[2], nld=extractor.nld[2])
simnorm.plot()
plt.show()


normlog = om.introspection.get_logger('ensembleNormalizer', 'DEBUG')
ensemblenorm_sim = om.EnsembleNormalizer(extractor=extractor, normalizer_gsf=gsfnorm,normalizer_nld=nldnorm,regenerate=True)
ensemblenorm_sim.normalize()
```
The NormalizerSimultan manages to normalize a single instance of the Ensemble well. However when doing this for the entire ensemble it crashes.
```
2022-11-25 12:02:33,177 - ompy.ensembleNormalizer - INFO - Start normalization with 7 cpus
  0%|                                                                                                                                                                                        | 0/5 [00:00<?, ?it/s]Process ForkPoolWorker-8:
Traceback (most recent call last):
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/pool.py", line 110, in worker
    task = get()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/queues.py", line 357, in get
    return _ForkingPickler.loads(res)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
AttributeError: 'ExtrapolationModelLow' object has no attribute '__model'
Process ForkPoolWorker-9:
Traceback (most recent call last):
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/pool.py", line 110, in worker
    task = get()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/queues.py", line 357, in get
    return _ForkingPickler.loads(res)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
AttributeError: 'ExtrapolationModelLow' object has no attribute '__model'
Process ForkPoolWorker-10:
Traceback (most recent call last):
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/pool.py", line 110, in worker
    task = get()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/queues.py", line 357, in get
    return _ForkingPickler.loads(res)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
AttributeError: 'ExtrapolationModelLow' object has no attribute '__model'
Process ForkPoolWorker-11:
Traceback (most recent call last):
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/pool.py", line 110, in worker
    task = get()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/queues.py", line 357, in get
    return _ForkingPickler.loads(res)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
AttributeError: 'ExtrapolationModelLow' object has no attribute '__model'
Process ForkPoolWorker-12:
Traceback (most recent call last):
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/pool.py", line 110, in worker
    task = get()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/multiprocess/queues.py", line 357, in get
    return _ForkingPickler.loads(res)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/johan/anaconda3/envs/ompy/lib/python3.7/site-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
AttributeError: 'ExtrapolationModelLow' object has no attribute '__model'
```

I suspect this is related to an issue with multiprocessing. python version = 3.7.12

**Comment by jelarsso** [comment]
Issue not reproduced in python version 3.11 so this is not an issue in newest version of python.
